# Python image
FROM python:3.10.6-buster

# Copy API, requirements and the makefile
# Syntax COPY [source] [destination]
COPY setup.py /setup.py
COPY requirements.txt /requirements.txt
COPY requirements-large.txt /requirements-large.txt
COPY scripts/*.py /scripts/
COPY data_collection/*.py /data_collection/
COPY reddit-sentiment-400608-24bc7c65b16e.json /app/credentials.json

# Set environment variable to read/write the BQ database
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

# Upgrade pip
RUN pip install --upgrade pip
# Install requirements
RUN pip install requirements.txt
RUN pip install requirements-large.txt
# Install local package
RUN pip install .

# Run the initialise bert script so bert depdancies are built into the image
RUN python scripts/initialise_bert.py

# Host the API
CMD uvicorn data_collection.data_collection_api:app --host 0.0.0.0 --port $PORT
