# Python image
# FROM python:3.10.6-buster
# Actually use Pytorch image
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

WORKDIR /

# Copy API, requirements and the makefile
# Syntax COPY [source] [destination]
COPY setup.py /setup.py
COPY requirements.txt /requirements1.txt
COPY scripts/*.py /scripts/
COPY data_collection/*.py /data_collection/
COPY reddit-sentiment-400608-24bc7c65b16e.json /app/credentials.json
COPY reddit_sentiment_modules /reddit_sentiment_modules

# Set environment variable to read/write the BQ database
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

# Upgrade pip
RUN pip install --upgrade pip
# Install requirements
RUN pip install -r requirements1.txt
# Install local package
RUN pip install .

# Make the directory for the models
RUN mkdir -p /app/cache

# Run the initialise bert script so bert depdancies are built into the image
RUN python scripts/initialise_bert.py

# Host the API
CMD uvicorn data_collection.data_collection_api:app --host 0.0.0.0 --port $PORT
