# Python image
FROM python:3.10.6-buster

# Copy API, requirements and the makefile
# Syntax COPY [source] [destination]
COPY setup.py /setup.py
COPY API /API
COPY requirements.txt /requirements.txt
COPY requirements-large1.txt /requirements-large1.txt
COPY requirements-large2.txt /requirements-large2.txt
COPY scripts/initialise_bert.py /scripts/initialise_bert.py

# Upgrade pip
RUN pip install --upgrade pip
# Install requirements
RUN pip install -r requirements.txt
RUN pip install -r requirements-large1.txt
RUN pip install -r requirements-large2.txt
# Install local package
RUN pip install .

# Run the initialise bert script so bert depdancies are built into the image
RUN python scripts/initialise_bert.py

# Host the API
CMD uvicorn API.fastapi:app --host 0.0.0.0 --port $PORT
