# Pytorch base image
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

WORKDIR /

# Copy API, requirements and the makefile
# Syntax COPY [source] [destination]
COPY API /API
COPY scripts/*.py /scripts/
COPY requirements1.txt /requirements1.txt
COPY scripts/initialise_bert.py /scripts/initialise_bert.py
COPY reddit-sentiment-400608-24bc7c65b16e.json /app/credentials.json

# Set environment variable to read/write the BQ database
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

# Upgrade pip
RUN pip install --upgrade pip
# Install requirements
RUN pip install -r requirements1.txt

# Make the directory for the models
RUN mkdir -p /app/cache

# Run the initialise bert script so bert depdancies are built into the image
RUN python scripts/initialise_bert.py

# Host the API
CMD uvicorn API.api:app --host 0.0.0.0 --port $PORT
